upstream tunnel {
	server 127.0.0.1:8000;
}
server {
	server_name 200.131.5.61 bq.mat.br;
	client_max_body_size 50M;
	access_log /home/ifnmg/www/bqm/logs/access.log;
	error_log /home/ifnmg/www/bqm/logs/error.log;
	location / {
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $http_host;
		proxy_redirect off;
		proxy_pass http://tunnel;
	}

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/bq.mat.br/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/bq.mat.br/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = bq.mat.br) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	server_name 200.131.5.61 bq.mat.br;
    return 404; # managed by Certbot


}