# Generated by Django 3.0.7 on 2021-02-06 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('etapa', models.AutoField(primary_key=True, serialize=False)),
                ('etapa_nome', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['etapa'],
            },
        ),
        migrations.CreateModel(
            name='NivelDeDificuldade',
            fields=[
                ('nivel_de_dificuldade', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_de_dificuldade_nome', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Nível de dificuldade',
                'verbose_name_plural': 'Níveis de dificuldade',
                'ordering': ['nivel_de_dificuldade'],
            },
        ),
        migrations.CreateModel(
            name='ObjetoDeConhecimento',
            fields=[
                ('etapa', models.IntegerField()),
                ('unidade_tematica', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('objeto_de_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('objeto_de_conhecimento_nome', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Objeto de conhecimento',
                'verbose_name_plural': 'Objetos de conhecimento',
                'ordering': ['objeto_de_conhecimento'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeTematica',
            fields=[
                ('etapa', models.IntegerField()),
                ('unidade_tematica', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('unidade_tematica_nome', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Unidade temática',
                'verbose_name_plural': 'Unidades temáticas',
                'ordering': ['unidade_tematica'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('etapa', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('unidade_tematica', models.IntegerField()),
                ('objeto_de_conhecimento', models.IntegerField()),
                ('nivel_de_dificuldade', models.IntegerField()),
                ('imagem', models.IntegerField(blank=True, null=True)),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('cadastro_pelo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Imprimir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('qids', models.CharField(max_length=500)),
                ('cadastro_pelo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imprimir', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imprimir',
                'verbose_name_plural': 'Imprimir',
                'ordering': ['id'],
            },
        ),
    ]
