# Generated by Django 3.0.7 on 2020-12-17 23:15

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=upload.models.path)),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'ordering': ['id'],
            },
        ),
    ]
